apiVersion: promoter.argoproj.io/v1alpha1
kind: ScmProvider
metadata:
  name: github
  namespace: promoter-system
spec:
  secretRef:
    name: github-app-promoter
  github:
    appID: 1300879
    installationID: 67574271