apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-staging-v1-0-1
spec:
  project: default
  source:
    repoURL: https://github.com/BenHesketh21/gitops-release-branches-argo.git
    targetRevision: HEAD
    path: charts/app1
    helm:
      releaseName: app1
      valueFiles:
      - values.yaml
      - values/staging/base.yml
      - values/staging/v1.0.1/version.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging-v1-0-1
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-staging-v1-0-1
spec:
  project: default
  source:
    repoURL: https://github.com/BenHesketh21/gitops-release-branches-argo.git
    targetRevision: HEAD
    path: charts/app2
    helm:
      releaseName: app2
      valueFiles:
      - values.yaml
      - values/staging/base.yml
      - values/staging/v1.0.1/version.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging-v1-0-1
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true