apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: app1-tenant1-test-main:apps/Deployment:/app1
  name: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - env:
            - name: TENANT
              value: yoga
            - name: ENV
              value: test
            - name: BOOM
              value: hello
          image: ghcr.io/benhesketh21/app1:main-11922033263
          imagePullPolicy: IfNotPresent
          name: app1
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
