apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: TENANT1
            value: {{ .Values.env.tenant }}
          {{ if .Values.newEnvs.enabled -}}
          - name: ENV
            value: {{ .Values.env.name }}
          - name: BOOM
            value: hello
          {{ end -}}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
