# Default values for app1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: ghcr.io/benhesketh21
  repository: app2
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "main-8960719671"
service:
  type: ClusterIP
  port: 80

env:
  name: test
  tenant: yoga
