kind: ClusterAnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: pass
spec:
  metrics:
  - name: pass
    count: 1
    interval: 5s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: pass
                image: ghcr.io/linuxcontainers/alpine:latest
                command: ["sh", "-c"]
                args: ["exit 0"]
              restartPolicy: Never
          backoffLimit: 0
---
kind: ClusterAnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: fail
spec:
  metrics:
  - name: fail
    count: 1
    interval: 5s
    failureLimit: 0
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: fail
                image: ghcr.io/linuxcontainers/alpine:latest
                command: ["sh", "-c"]
                args: ["exit 1"]
              restartPolicy: Never
          backoffLimit: 0