kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: pass
  namespace: test-main
spec:
  metrics:
  - name: pass
    count: 2
    interval: 5s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: fail
                image: ghcr.io/linuxcontainers/alpine:latest
                command: ["sh", "-c"]
                args: ["exit 0"]
              restartPolicy: Never
          backoffLimit: 0