apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: staging-v0-0-1-warehouse
  namespace: staging-v0-0-1
spec:
  freightCreationPolicy: Automatic
  interval: 1h0m
  subscriptions:
    - image:
        discoveryLimit: 2
        imageSelectionStrategy: NewestBuild
        repoURL: ghcr.io/benhesketh21/app1
        allowTags: v0.0.1-*
    - image:
        discoveryLimit: 2
        imageSelectionStrategy: NewestBuild
        repoURL: ghcr.io/benhesketh21/app2
        allowTags: v0.0.1-*