apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: staging-v0-0-1
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: staging-v0-0-1-warehouse
  namespace: staging-v0-0-1
spec:
  freightCreationPolicy: Automatic
  interval: 1h0m
  subscriptions:
    - image:
        discoveryLimit: 2
        imageSelectionStrategy: NewestBuild
        repoURL: ghcr.io/benhesketh21/app1
        allowTags: v0.0.1-*
    - image:
        discoveryLimit: 2
        imageSelectionStrategy: NewestBuild
        repoURL: ghcr.io/benhesketh21/app2
        allowTags: v0.0.1-*
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant1-staging-v0-0-1
  namespace: staging-v0-0-1
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: staging-v0-0-1-warehouse
    sources:
      direct: true
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/BenHesketh21/gitops-release-branches-argo
      writeBranch: main
      helm:
        images:
        - image: ghcr.io/benhesketh21/app1
          key: image.tag
          value: Tag
          valuesFilePath: charts/app1/values/staging/v0.0.1/tenant1/version.yml
        - image: ghcr.io/benhesketh21/app2
          key: image.tag
          value: Tag
          valuesFilePath: charts/app2/values/staging/v0.0.1/tenant1/version.yml
    argoCDAppUpdates:
    - appName: app1-tenant1-staging-v0-0-1
      appNamespace: argocd
    - appName: app2-tenant1-staging-v0-0-1
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant1-prod
  namespace: staging-v0-0-1
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: staging-v0-0-1-warehouse
    sources:
      stages:
      - tenant1-staging-v0-0-1
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/BenHesketh21/gitops-release-branches-argo
      writeBranch: main
      helm:
        images:
        - image: ghcr.io/benhesketh21/app1
          key: image.tag
          value: Tag
          valuesFilePath: charts/app1/values/prod/tenant1/version.yml
        - image: ghcr.io/benhesketh21/app2
          key: image.tag
          value: Tag
          valuesFilePath: charts/app2/values/prod/tenant1/version.yml
    argoCDAppUpdates:
    - appName: app1-tenant1-prod
      appNamespace: argocd
    - appName: app2-tenant1-prod
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant2-staging-v0-0-1
  namespace: staging-v0-0-1
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: staging-v0-0-1-warehouse
    sources:
      direct: true
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/BenHesketh21/gitops-release-branches-argo
      writeBranch: main
      helm:
        images:
        - image: ghcr.io/benhesketh21/app1
          key: image.tag
          value: Tag
          valuesFilePath: charts/app1/values/staging/v0.0.1/tenant2/version.yml
        - image: ghcr.io/benhesketh21/app2
          key: image.tag
          value: Tag
          valuesFilePath: charts/app2/values/staging/v0.0.1/tenant2/version.yml
    argoCDAppUpdates:
    - appName: app1-tenant2-staging-v0-0-1
      appNamespace: argocd
    - appName: app2-tenant2-staging-v0-0-1
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant2-prod
  namespace: staging-v0-0-1
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: staging-v0-0-1-warehouse
    sources:
      stages:
      - tenant2-staging-v0-0-1
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/BenHesketh21/gitops-release-branches-argo
      writeBranch: main
      helm:
        images:
        - image: ghcr.io/benhesketh21/app1
          key: image.tag
          value: Tag
          valuesFilePath: charts/app1/values/prod/tenant2/version.yml
        - image: ghcr.io/benhesketh21/app2
          key: image.tag
          value: Tag
          valuesFilePath: charts/app2/values/prod/tenant2/version.yml
    argoCDAppUpdates:
    - appName: app1-tenant2-prod
      appNamespace: argocd
    - appName: app2-tenant2-prod
      appNamespace: argocd