apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant1-staging-v0-0-1
  namespace: staging-v0-0-1
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: staging-v0-0-1-warehouse
    sources:
      direct: true
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/BenHesketh21/gitops-release-branches-argo
      writeBranch: main
      helm:
        images:
        - image: ghcr.io/benhesketh21/app1
          key: image.tag
          value: Tag
          valuesFilePath: charts/app1/values/staging/v0.0.1/version.yml
        - image: ghcr.io/benhesketh21/app2
          key: image.tag
          value: Tag
          valuesFilePath: charts/app2/values/staging/v0.0.1/version.yml
    argoCDAppUpdates:
    - appName: app1-staging-v0-0-1
      appNamespace: argocd
    - appName: app2-staging-v0-0-1
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant1-prod
  namespace: staging-v0-0-1
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: staging-v0-0-1-warehouse
    sources:
      stages:
      - tenant1-staging-v0-0-1
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/BenHesketh21/gitops-release-branches-argo
      writeBranch: main
      helm:
        images:
        - image: ghcr.io/benhesketh21/app1
          key: image.tag
          value: Tag
          valuesFilePath: charts/app1/values/prod/version.yml
        - image: ghcr.io/benhesketh21/app2
          key: image.tag
          value: Tag
          valuesFilePath: charts/app2/values/prod/version.yml
    argoCDAppUpdates:
    - appName: app1-prod
      appNamespace: argocd
    - appName: app2-prod
      appNamespace: argocd