apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: test-main-warehouse
  namespace: test-main
spec:
  freightCreationPolicy: Automatic
  interval: 1h0m
  subscriptions:
    - image:
        discoveryLimit: 2
        imageSelectionStrategy: NewestBuild
        repoURL: ghcr.io/benhesketh21/app1
        allowTags: main-*
    - image:
        discoveryLimit: 2
        imageSelectionStrategy: NewestBuild
        repoURL: ghcr.io/benhesketh21/app2
        allowTags: main-*