apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: test-main
spec:
  promotionPolicies:
  - autoPromotionEnabled: true
    stage: tenant1-test-main
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant1-test-main
  namespace: test-main
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: test-main-warehouse
    sources:
      direct: true
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/BenHesketh21/gitops-release-branches-argo
      writeBranch: main
      helm:
        images:
        - image: ghcr.io/benhesketh21/app1
          key: image.tag
          value: Tag
          valuesFilePath: charts/app1/values/test/main/version.yml
        - image: ghcr.io/benhesketh21/app2
          key: image.tag
          value: Tag
          valuesFilePath: charts/app2/values/test/main/version.yml
    argoCDAppUpdates:
    - appName: app1-tenant1-test-main
      appNamespace: argocd
    - appName: app2-tenant1-test-main
      appNamespace: argocd