apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: test-main
spec:
  promotionPolicies:
  - autoPromotionEnabled: true
    stage: tenant1-test-main
  - autoPromotionEnabled: true
    stage: tenant2-test-main
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: test-main-warehouse
  namespace: test-main
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - image:
        discoveryLimit: 1
        imageSelectionStrategy: NewestBuild
        repoURL: ghcr.io/benhesketh21/app1
        allowTags: main-*
    - image:
        discoveryLimit: 1
        imageSelectionStrategy: NewestBuild
        repoURL: ghcr.io/benhesketh21/app2
        allowTags: main-*
    - git:
        repoURL: https://github.com/BenHesketh21/gitops-release-branches-argo
        includePaths:
        - charts/app1
        - charts/app2
        excludePaths:
        - glob:charts/app1/values/*/version.yml
        - glob:charts/app2/values/*/version.yml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant1-test-main
  namespace: test-main
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: test-main-warehouse
    sources:
      direct: true
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/BenHesketh21/gitops-release-branches-argo
      writeBranch: main
      helm:
        images:
        - image: ghcr.io/benhesketh21/app1
          key: image.tag
          value: Tag
          valuesFilePath: charts/app1/values/test/main/tenant1/version.yml
        - image: ghcr.io/benhesketh21/app2
          key: image.tag
          value: Tag
          valuesFilePath: charts/app2/values/test/main/tenant1/version.yml
    argoCDAppUpdates:
    - appName: app1-tenant1-test-main
      appNamespace: argocd
    - appName: app2-tenant1-test-main
      appNamespace: argocd
  verification:
    analysisTemplates:
    - name: pass
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tenant2-test-main
  namespace: test-main
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: test-main-warehouse
    sources:
      direct: true
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/BenHesketh21/gitops-release-branches-argo
      writeBranch: main
      helm:
        images:
        - image: ghcr.io/benhesketh21/app1
          key: image.tag
          value: Tag
          valuesFilePath: charts/app1/values/test/main/tenant2/version.yml
        - image: ghcr.io/benhesketh21/app2
          key: image.tag
          value: Tag
          valuesFilePath: charts/app2/values/test/main/tenant2/version.yml
    argoCDAppUpdates:
    - appName: app1-tenant2-test-main
      appNamespace: argocd
    - appName: app2-tenant2-test-main
      appNamespace: argocd
  verification:
    analysisTemplates:
    - name: pass