on:
  pull_request:
    types: [opened, synchronize]
  
permissions:
  contents: read
  pull-requests: write

name: Diff GitOps Environments

jobs:
  diff-env:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR
      uses: actions/checkout@v3
      with:
        path: pr
    - name: Checkout Target of PR
      uses: actions/checkout@v3
      with:
        path: target
        ref: ${{ github.event.pull_request.base.ref }}
    - run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
        helm template app tenant1-app1 pr/charts/app1 -f pr/charts/app1/values.yaml -f pr/charts/app1/values/test/base.yml -f pr/charts/app1/values/test/main/tenant1/version.yml > tenant1-app1-pr.yml
        helm template app tenant1-app1 target/charts/app1 -f target/charts/app1/values.yaml -f target/charts/app1/values/test/base.yml -f target/charts/app1/values/test/main/tenant1/version.yml > tenant1-app1-target.yml
        diff -U 7 tenant1-app1-pr.yml tenant1-app1-target.yml > tenant1-app1-changes.diff || true
    - run: |
        wget https://raw.githubusercontent.com/kostis-codefresh/kustomize-github-preview-diff/main/pr-comment-template.txt
        sed  's/DESCRIPTION_HERE/tenant1-app1/g' pr-comment-template.txt > tenant1-app1-diff.txt
        sed  -e "/DIFF_HERE/{r qa-changes.diff" -e "d}" tenant1-app1-diff.txt > tenant1-app1-result.txt
        cat tenant1-app1-result.txt > comment.txt
    - name: comment PR
      uses: machine-learning-apps/pr-comment@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: comment.txt