# This is a basic workflow to help you get started with Actions

name: test-main

on:
  repository_dispatch:
    types: [test_release]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-release-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64 -O ../yq
      - name: Get Latest Versions
        run: |
          export GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          apps=("app1" "app2")
          echo "{}" > stack_versions.json
          for app in "${apps[@]}"
          do
            latestRelease=$(gh release list -R BenHesketh21/gitops-release-branches --json name,tagName,isLatest,createdAt -q "[.[]|select(.tagName | startswith(\"${app}-main\"))]|.[0]")
            echo ${latestRelease} | jq .
            version=$(echo "${latestRelease}" | jq -r '.tagName')
            version_without_app=$(echo ${version} | sed "s ${app}-  g")
            echo "version: ${version_without_app}"
            echo "${app}"
            yq e -iP ".${app}=\"${version_without_app}\"" stack_versions.json -o=json
            cat stack_versions.json | jq .
          done
      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: stack_versions_artifact
      
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: stack_versions.json
  # This workflow contains a single job called "build"
  app1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: get-release-versions

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: stack_versions_artifact
    
      - name: install yq
        run: |
          ls
          wget https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64 -O ../yq
      - name: Update App 1 Version
        run: |
          version=$(jq .app1 $GITHUB_WORKSPACE/stack_versions.yml)
          ../yq w -i charts/app1/values.yaml 'image.tag' "${version/app1/}"
          git add .
          git commit -m "[skip-ci] Updating app1 to {version/app1/}"
          git push
          
