# This is a basic workflow to help you get started with Actions

name: test-main

on:
  workflow_run:
    workflows:
    - Build App 1
    - Build App 2
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  app1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install YQ
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64 -O ../yq
      - name: Update App 1 Version
        run: |
          ../yq w -i charts/app1/values.yaml 'image.tag' '${{ github.event.workflow_run.head_branch }}-${{ github.event.workflow_run.run_id }}'
          git add .
          git commit -m "[skip-ci] Updating app1 to ${{ github.event.workflow_run.head_branch }}-${{ github.event.workflow_run.run_id }}"
          git push
          
